### ISSUE TITLE
Support for swift 2.2

### ISSUE THREAD

**Issue by shartf** [marcomasser/LaunchBarActions#1]
Hello Marco, 

The "Create new playground" scripts are not working with the current version of Swift (2.2) Any chance they will be upgraded?

**Comment by marcomasser** [comment]
Hello @shartf,

I’ve been meaning to update them for quite a while. I hope to find the time to do that soon!

**Comment by marcomasser** [comment]
Hey, @shartf, I just updated both “Create New Playground” actions for OS X and iOS. Enjoy!

**Comment by shartf** [comment]
Vielen Dank! :)
